2
marcbloc/The-game---Javascript pull request #1
Opened 2017-05-05 21:01 UTC by marcbloc

2017-05-07 08:24 UTC, matwjablonski requested changes

2017-05-07 08:24 UTC, matwjablonski commented on index.html
> +	<neta charset="UTF-8">
`<neta>` not exist in html doc

2017-05-07 08:24 UTC, matwjablonski commented on index.html
> +	</head>
one tab to remove

2017-05-07 08:24 UTC, matwjablonski commented on index.html
> +	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" />
on end of tag link you don't need to add `/`

2017-05-07 08:24 UTC, matwjablonski commented on js/scripts.js
> +		if (playerPick == computerPick) {
better will be compare by `===` instead of `==`

2017-05-07 08:24 UTC, matwjablonski commented on js/scripts.js
> +			(computerPick == 'rock' && playerPick == 'scissors') ||
`===` instead of `==`

2017-05-07 08:24 UTC, matwjablonski commented on js/scripts.js
> +			(computerPick == 'scissors' && playerPick == 'paper') ||
`===` instead of `==`

2017-05-07 08:24 UTC, matwjablonski commented on js/scripts.js
> +			(computerPick == 'paper' && playerPick == 'rock')) {
`===` instead of `==`

2017-05-07 08:24 UTC, matwjablonski commented on js/scripts.js
> +		if (winnerIs == 'player') {
`===` instead of `==`

2017-05-07 08:24 UTC, matwjablonski commented on js/scripts.js
> +		} else if (winnerIs == 'computer') {
`===` instead of `==`

2017-05-07 08:24 UTC, matwjablonski commented on js/scripts.js
> +	if (player.score == 10) {
`===` instead of `==`

2017-05-07 08:24 UTC, matwjablonski commented on js/scripts.js
> +	} else if (computer.score == 10) {
`===` instead of `==`

2017-05-07 14:33 UTC, marcbloc commented
corrected

2017-05-08 08:17 UTC, matwjablonski requested changes

2017-05-08 08:17 UTC, matwjablonski commented on js/scripts.js
> +			(computerPick === 'rock' && playerPick == 'scissors') ||
second statement also should be changed :)

2017-05-09 07:26 UTC, matwjablonski approved these changes

2017-06-20 16:42 UTC, merged